### ISSUE TITLE
【bug】偶尔出现的歌词时间标签

### ISSUE THREAD

**Issue by Paper-Folding** [lyswhut/lrc-file-parser#10]
## 截图1：网页显示效果
![image](https://user-images.githubusercontent.com/49343539/135293384-a8bd5fad-eef1-4749-b1da-4056b666a529.png)
## 截图2：控制台变量截图1（lyrics raw string）
![屏幕截图 2021-09-29 225156](https://user-images.githubusercontent.com/49343539/135293799-b03f8310-5691-4ae9-87da-cf13d6c1085e.png)
## 截图3：控制台变量截图2 （lyrics parsed array）
![屏幕截图 2021-09-29 225442](https://user-images.githubusercontent.com/49343539/135294291-e1babea1-585b-4be2-b49f-c4661077487d.png)

## 截图4：lrc歌词文件，使用hex editor打开，发现出问题行确实以四个0D（即'\r'）结尾：
![屏幕截图 2021-09-29 225938](https://user-images.githubusercontent.com/49343539/135295350-0579fd2d-e6ff-4d83-a57c-0ef16a492239.png)
## 截图5：歌词lrc文件以普通文本的形式打开，没有问题：
![image](https://user-images.githubusercontent.com/49343539/135295628-e4e96b04-b82b-4002-8455-743b0b993e28.png)

### _稍后我提交一份我的问题歌词文件，或者也可直接传入仅以'\r'字符结尾的歌词行来重现问题。希望大大修正。_

**Comment by Paper-Folding** [comment]
问题lrc文件链接：[link](https://gist.github.com/Paper-Folding/d332d7d170a300df767b8a740db5b20f)，注意，该文件以gbk格式编码，使用文件api读取时注意使用正确的编码读取；下载请以raw的形式下载文件，否则可能改变其中的\r编码。（突然发现我好啰嗦😂）

**Comment by lyswhut** [comment]
`\r`本来就不是换行符啊，windows下`\r\n`才是换行符，Unix下`\n`是换行符，是你歌词文件内容的问题，你可以将整个歌词文件的`\r`替换成`\n`，然后按`\n`切割，最后遍历切割后的数组去除掉空行再按`\n`将字符串数组拼接回整单个字符串即可

**Comment by Paper-Folding** [comment]
> `\r`本来就不是换行符啊，windows下`\r\n`才是换行符，Unix下`\n`是换行符，是你歌词文件内容的问题，你可以将整个歌词文件的`\r`替换成`\n`，然后按`\n`切割，最后遍历切割后的数组去除掉空行再按`\n`将字符串数组拼接回整单个字符串即可

好吧其实这样也行，我现在就这么解决的🐶

**Comment by lyswhut** [comment]
算了，我还是处理下吧，似乎Mac OS的换行符就一个`\r`，坑

**Comment by lyswhut** [comment]
试试v1.1.3，该版本添加了对`\r`的处理

**Comment by Paper-Folding** [comment]
问题在新版本得到解决。
