### ISSUE TITLE
空行被parser剔除

### ISSUE THREAD

**Issue by Paper-Folding** [lyswhut/lrc-file-parser#11]
（又是我，哈哈哈......）
#### 形如下面这样的歌词，第二行空行歌词被lyric parser直接剔除
```
[00:05.00]5秒后进入空行
[00:10.00] 
[00:20.00]此行于空行之后
```

**Comment by Paper-Folding** [comment]
（我这次自己改了下大大的源码，大大可以考虑下是否merge：#12）

**Comment by lyswhut** [comment]
为什么要保留空行？没有内容的行意义何在？

**Comment by Paper-Folding** [comment]
> 为什么要保留空行？没有内容的行意义何在？

空行代表歌曲中存在的不需要演唱的纯音乐部分。
以上面的歌词为例，该歌词的第一行于 第5秒 开始演唱，第10秒结束该行歌词的演唱，第10~20秒属于纯音乐，是无需演唱的过场，第20秒开始第3行歌词的演唱。
不知道大大有没有做过歌词文件，但是这个技巧被许多制作者使用。

**Comment by lyswhut** [comment]
你做成选项的形式吧，默认去除空行，isRemoveBlankLine

**Comment by Paper-Folding** [comment]
已改为选项并在README中添加了此选项说明😉

**Comment by lyswhut** [comment]
可以试试当前最新的v1.2.1

**Comment by Paper-Folding** [comment]
> 可以试试当前最新的v1.2.1

好的，大大国庆快乐哟~

**Comment by Paper-Folding** [comment]
大大，你最近的两次升级都忘了为translation lines提供支持，见 #13

**Comment by lyswhut** [comment]
已经合并并发布v1.2.2了

**Comment by Paper-Folding** [comment]
好的
