### ISSUE TITLE
mpvue中使用报错

### ISSUE THREAD

**Issue by yzh990918** [lyswhut/lrc-file-parser#3]
![](https://image.yangxiansheng.top/img/QQ截图20200316171332.png?imagelist)

![](https://image.yangxiansheng.top/img/QQ截图20200316171321.png?imagelist)

我改如何使用这个插件获取到当前播放的歌词

**Comment by lyswhut** [comment]
你看过demo的代码了吗？
你设置歌词的时候传的东西是怎么样的？

**Comment by yzh990918** [comment]
![](https://image.yangxiansheng.top/img/QQ截图20200317131346.png?imagelist)

传入的是这个字段。demo代码大致看了

**Comment by lyswhut** [comment]
你将这个歌词贴出来我试试
调用`audioContext.onplay`出错，插件并没有这个方法

**Comment by yzh990918** [comment]
"lyric": "[00:04.050]\n[00:12.570]难以忘记初次见你\n[00:16.860]一双迷人的眼睛\n[00:21.460]在我脑海里\n[00:23.960]你的身影 挥散不去\n[00:30.160]握你的双手感觉你的温柔\n[00:34.940]真的有点透不过气\n[00:39.680]你的天真 我想珍惜\n[00:43.880]看到你受委屈 我会伤心\n[00:48.180]喔\n[00:50.340]只怕我自己会爱上你\n[00:55.070]不敢让自己靠的太近\n[00:59.550]怕我没什么能够给你\n[01:04.030]爱你也需要很大的勇气\n[01:08.190]只怕我自己会爱上你\n[01:12.910]也许有天会情不自禁\n[01:17.380]想念只让自己苦了自己\n[01:21.840]爱上你是我情非得已\n[01:28.810]难以忘记初次见你\n[01:33.170]一双迷人的眼睛\n[01:37.700]在我脑海里 你的身影 挥散不去\n[01:46.360]握你的双手感觉你的温柔\n[01:51.120]真的有点透不过气\n[01:55.910]你的天真 我想珍惜\n[02:00.150]看到你受委屈 我会伤心\n[02:04.490]喔\n[02:06.540]只怕我自己会爱上你\n[02:11.240]不敢让自己靠的太近\n[02:15.750]怕我没什么能够给你\n[02:20.200]爱你也需要很大的勇气\n[02:24.570]只怕我自己会爱上你\n[02:29.230]也许有天会情不自禁\n[02:33.680]想念只让自己苦了自己\n[02:38.140]爱上你是我情非得已\n[03:04.060]什么原因 耶\n[03:07.730]我竟然又会遇见你\n[03:13.020]我真的真的不愿意\n[03:16.630]就这样陷入爱的陷阱\n[03:20.700]喔\n[03:22.910]只怕我自己会爱上你\n[03:27.570]不敢让自己靠的太近\n[03:32.040]怕我没什么能够给你\n[03:36.560]爱你也需要很大的勇气\n[03:40.740]只怕我自己会爱上你\n[03:45.460]也许有天会情不自禁\n[03:49.990]想念只让自己苦了自己\n[03:54.510]爱上你是我情非得已\n[03:58.970]爱上你是我情非得已\n[04:03.000]\n"

**Comment by yzh990918** [comment]
![](https://image.yangxiansheng.top/img/QQ截图20200317134304.png?imagelist)

我看你这么写的 我就写进去了。我在小程序中是要监听onPlay()调用 还是监听onTimeUpdate()调用？求指教

**Comment by lyswhut** [comment]
我在demo页设置你这段歌词时可以正常播放的：
![image](https://user-images.githubusercontent.com/20365169/76825921-2aa2a600-6856-11ea-8843-030304ee136f.png)

你要监听`playing`事件播放，并且还要监听所有可能导致暂停播放的事件，你可以参考下面的事件监听：
https://github.com/lyswhut/lx-music-desktop/blob/b04c6762886af9c8bdda8579cbefa82479da69e1/src/renderer/components/core/Player.vue#L205

暂停、缓冲、出错、播放完毕

**Comment by yzh990918** [comment]
好的 多谢 回去试试
