### ISSUE TITLE
need to display muti lines of lycis..

### ISSUE THREAD

**Issue by jomin398** [lyswhut/lrc-file-parser#8]
``
[00:00.00] eng
[00:00.00] rom
[00:00.00] jp

[00:03.10] eng
[00:03.10] rom
[00:03.10] jp
.....
``
i had muti-lined lrc file like this
how to use this module for display all 3 line?

**Comment by lyswhut** [comment]
Sorry, this module does not support displaying rows with the same time at the same time.
For rows with the same time, the previous ones will be overwritten by the next ones.
But it supports displaying lyrics translation (currently only supports one translation), you need to input the translated lyrics separately
Original lyrics: 
```
[00:00.485]Rick Astley - Never Gonna Give You Up
[00:19.311]We're no strangers to love
[00:23.206]You know the rules and so do I
[00:27.495]A full commitment's what I'm thinking of
[00:31.743]You wouldn't get this from any other guy
[00:35.709]I just wanna tell you how I'm feeling
```
translation lyrics: 
```
[00:00.485]
[00:19.311]我们都不是恋爱的新手
[00:23.206]你我都懂得那些规则
[00:27.495]我只希望可以全力以赴
[00:31.743]你不会从其他男人那里得到这样的爱情
[00:35.709]我只想告诉你我的感受
```
```js
var lrc = new Lyric({
  onPlay: function (line, text) {
    console.log(lrcLines[line].text + '\n' + (lrcLines[line].translation || ''))
  },
  onSetLyric: function (lines) {
    console.log(lines)
  }
})
lrc.setLyric(lyric, translationLyric)
```
Output result:

![image](https://user-images.githubusercontent.com/20365169/129133899-404b9f99-5d4b-4cda-8e08-8dfe3c08aef9.png)
![image](https://user-images.githubusercontent.com/20365169/129134588-a75da9d6-4879-4b28-9e23-5d62a02e8616.png)

You can watch the demo:
<https://lyswhut.github.io/lrc-file-parser/dist/index.html>

**Comment by lyswhut** [comment]
Update:

Since v2.0.0, the parsing of multiple extended lyrics is supported:

```js
var lrcLines = []
var lrc = new Lyric({
  onPlay: function (line, text) {
    console.log(lrcLines[line].text + '\n' + lrcLines[line].extendedLyrics.join('\n')))
  },
  onSetLyric: function (lines) {
    lrcLines = lines
    console.log(lines)
  }
})
lrc.setLyric(lyric, [translationLyric1, translationLyric2, translationLyric3])

```
