### ISSUE TITLE
Could you please add an api to stop playing lyric? 希望添加一个api使得歌词能够停止播放。

### ISSUE THREAD

**Issue by Paper-Folding** [lyswhut/lrc-file-parser#9]
### 另外，你的歌词解析器非常强大又好用，我使用你的解析器实现了这些年来一直想实现的网页音乐播放器（带歌词实时滚动与高亮）。很感谢你的辛勤付出，祝你生活愉快！

**Comment by lyswhut** [comment]
没看懂你想要停止功能的实际用处，
对于本模块来说，停止跟暂停都是一样的，因为每次播放都是需要你传入当前的播放时间，
不用的话，就直接暂停就行了，没必要重置此模块里面的状态

**Comment by Paper-Folding** [comment]
> 没看懂你想要停止功能的实际用处，
> 对于本模块来说，停止跟暂停都是一样的，因为每次播放都是需要你传入当前的播放时间，
> 不用的话，就直接暂停就行了，没必要重置此模块里面的状态

因为使用`play(0)`依旧会播放第一句歌词，停止后不该激活任何歌词，应当与调用`setLyric`后的状态一致。

**Comment by lyswhut** [comment]
我的意思是你想调停止的时候调暂停不也是一样的吗？
你为啥想要重置里面的状态？

**Comment by Paper-Folding** [comment]
大大，我可能阐述得不是很清楚，停止是指 __暂停__ 并设置 __播放时刻__ 为 __0__。

**Comment by lyswhut** [comment]
我的意思是你为啥想要把它的内部时间改为0？
因为每次都会要求传入当前播放的时间，重不重置里面的时间都是一样的。
比如你现在播放到35秒，然后暂停了，
然后恢复播放的时候，你调`play`时会传入当前恢复播放的时间，所以没必要重置里面的播放时间的好吧

**Comment by Paper-Folding** [comment]
大大，如果这个功能没必要的话我自己加一句js来判断一下就好了，哈哈。。

**Comment by lyswhut** [comment]
主要是如果你仅是为了重置里面的时间，那真的没有意义：https://github.com/lyswhut/lrc-file-parser/issues/9#issuecomment-903591902

**Comment by Paper-Folding** [comment]
这个是当然; 只是各大播放器都提供一个 方形格子作图标的停止按钮或者像poweramp那样长按暂停键来实现停止，我也顺便实现下罢了。不过我只要在停止播放触发时移除所有歌词行的 lyric-active 即可。我关了这个issue吧 ∧＿∧
